FROM centos:6

MAINTAINER wencan <i@wencan.org>

RUN yum install -y --nogpgcheck git subversion wget curl gcc make cmake automake autoconf libtool which zlib-devel openssl-devel \
    && yum clean all
